services:
  database:
    image: reinevan/home_library_service_db:1.0
    restart: always
    container_name: database
    ports: 
      - ${DB_PORT}:${DB_PORT}
    networks:
      - api_network
    volumes:
      - database_data:/var/lib/postgresql/data
      - database_logs:/var/log/postgresql
  app:
    image: reinevan/home_library_service:1.0
    restart: always
    container_name: app
    environment:
      - PORT=${PORT}
    ports: 
      - ${PORT}:${PORT}
    networks:
      - api_network
    volumes:
      - ./src:/app/src
volumes:
  database_data:
  database_logs:
networks:
  api_network:
    name: api_network
    driver: bridge